name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj
    - name: Build
      run: dotnet build ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj --no-restore
    - name: Test
      run: dotnet test ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj --no-build --verbosity normal
    - name: publish
     run: dotnet publish ${{github.workspace}}/WebApplication1/WebApplication1/WebApplication1.csproj -c Release -o dotnetcorewebapp
